"use client";
import React, { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { PricingApiClient, PricingApiError, type JsonObject, type PricingDraftDto, type PricingEditableDto, type PricingModel } from "@/presentation/api/pricing-api-client";
import { mapEditablePricingDraft, pricingErrorMessage, pricingModelLabel } from "@/presentation/pricing/pricing-view-models";
import { ErrorState, FormField, LoadingState, PageHeader, Panel, SelectInput, TextInput } from "@/presentation/components/ui/workspace-primitives";

const blankDraft: PricingDraftDto = { projectName: "", pricingModel: "PROJECT", currency: "USD", pricingConfigurationVersionId: "", pricingConfigurationVersion: 1, configurationSchemaVersion: 1, engineVersion: "", methodologyVersion: "", inputSnapshot: {}, outputSnapshot: {}, explanationSnapshot: {}, catalogSnapshot: {} };
const models: PricingModel[] = ["PROJECT", "FIXED_RETAINER", "PROFIT_SHARE_RETAINER", "HYBRID_RETAINER", "ADVISORY_HOURLY"];
const snapshots = ["inputSnapshot", "outputSnapshot", "explanationSnapshot", "catalogSnapshot"] as const;
function pretty(value: JsonObject) { return JSON.stringify(value, null, 2); }
function parseJson(value: string, label: string) { try { const parsed = JSON.parse(value); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error(); return parsed as JsonObject; } catch { throw new Error(`${label} must contain a valid JSON object.`); } }

export function PricingCreateScreen({ companyId }: { companyId: string }) {
  const router = useRouter(); const api = useMemo(() => new PricingApiClient(companyId), [companyId]);
  const [draft, setDraft] = useState(blankDraft); const [clientId, setClientId] = useState(""); const [ownerId, setOwnerId] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { const result = await api.create({ clientId: clientId.trim(), ownerId: ownerId.trim() || undefined, draft }); router.push(`/pricing-projects/${result.pricingProject.id}/edit?created=1`); } catch (caught) { setError(pricingErrorMessage(caught)); } finally { setBusy(false); } }
  return <PricingDraftForm title="New Pricing Project" description="Create the authoritative Draft. Pricing snapshots are submitted unchanged to Cotarion." draft={draft} setDraft={setDraft} clientId={clientId} setClientId={setClientId} ownerId={ownerId} setOwnerId={setOwnerId} error={error} busy={busy} submitLabel="Create Pricing Project" onSubmit={submit} />;
}

export function PricingEditScreen({ companyId, pricingProjectId }: { companyId: string; pricingProjectId: string }) {
  const api = useMemo(() => new PricingApiClient(companyId), [companyId]); const [source, setSource] = useState<PricingEditableDto | null>(null); const [draft, setDraft] = useState(blankDraft); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [conflict, setConflict] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const latest = await api.edit(pricingProjectId); setSource(latest); setDraft(latest.draft); setConflict(false); } catch (caught) { setError(pricingErrorMessage(caught)); } finally { setLoading(false); } }, [api, pricingProjectId]); useEffect(() => { void load(); }, [load]);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!source) return; setBusy(true); setError(null); setNotice(null); try { const result = await api.updateDraft(pricingProjectId, draft, source.concurrencyToken); setSource({ ...source, draft, concurrencyToken: result.concurrencyToken }); setNotice("Pricing Draft saved. You can continue editing with the refreshed Project state."); } catch (caught) { if (caught instanceof PricingApiError && caught.isConcurrencyConflict) setConflict(true); setError(pricingErrorMessage(caught)); } finally { setBusy(false); } }
  if (loading) return <LoadingState label="Loading editable Pricing Draft" />; if (!source) return <ErrorState title="Pricing Draft unavailable" message={error ?? "This Pricing Draft could not be loaded."} retry={() => void load()} />;
  const view = mapEditablePricingDraft(source);
  const canEdit = source.permittedActions.includes("EDIT_DRAFT");
  return <><PricingDraftForm title={`Edit ${source.estimateNumber}`} description={`${view.clientLabel} · ${view.ownerLabel}`} draft={draft} setDraft={setDraft} error={error} notice={notice} busy={busy} submitLabel="Save Draft" submitEnabled={canEdit} onSubmit={submit} />{!canEdit ? <div className="pricing-notice" role="status">This Pricing Draft is read-only in its current lifecycle state or for your current capabilities.</div> : null}{conflict ? <div className="pricing-conflict" role="alert"><strong>Reload required</strong><p>This Pricing Project changed after you loaded it. Reload the authoritative Draft before continuing; your update was not resubmitted.</p><button className="workspace-button" onClick={() => void load()} type="button">Reload latest Draft</button></div> : null}</>;
}

function PricingDraftForm({ title, description, draft, setDraft, clientId, setClientId, ownerId, setOwnerId, error, notice, busy, submitLabel, submitEnabled = true, onSubmit }: { title: string; description: string; draft: PricingDraftDto; setDraft: React.Dispatch<React.SetStateAction<PricingDraftDto>>; clientId?: string; setClientId?: (value: string) => void; ownerId?: string; setOwnerId?: (value: string) => void; error: string | null; notice?: string | null; busy: boolean; submitLabel: string; submitEnabled?: boolean; onSubmit: (event: React.FormEvent) => void }) {
  const [snapshotText, setSnapshotText] = useState(() => Object.fromEntries(snapshots.map((key) => [key, pretty(draft[key])])) as Record<typeof snapshots[number], string>); const [jsonError, setJsonError] = useState<string | null>(null);
  const { inputSnapshot, outputSnapshot, explanationSnapshot, catalogSnapshot } = draft;
  useEffect(() => { setSnapshotText({ inputSnapshot: pretty(inputSnapshot), outputSnapshot: pretty(outputSnapshot), explanationSnapshot: pretty(explanationSnapshot), catalogSnapshot: pretty(catalogSnapshot) }); }, [inputSnapshot, outputSnapshot, explanationSnapshot, catalogSnapshot]);
  function snapshot(key: typeof snapshots[number], value: string) { setSnapshotText((current) => ({ ...current, [key]: value })); try { const parsed = parseJson(value, key); setDraft((current) => ({ ...current, [key]: parsed })); setJsonError(null); } catch (caught) { setJsonError((caught as Error).message); } }
  return <div className="workspace-page"><PageHeader eyebrow="Project Pricing" title={title} description={description} actions={<Link className="workspace-button workspace-button-secondary" href="/pricing-projects">Cancel</Link>} />{notice ? <div className="pricing-notice" role="status">{notice}</div> : null}{error || jsonError ? <div className="proposal-command-error" role="alert">{jsonError ?? error}</div> : null}<form className="pricing-editor" onSubmit={onSubmit}>
    {setClientId ? <Panel title="Project ownership" description="Use Cotarion Client and owner identifiers supplied by your Company workspace."><div className="pricing-form-grid"><FormField label="Client ID"><TextInput required value={clientId} onChange={(event) => setClientId(event.target.value)} /></FormField><FormField label="Owner ID" hint="Leave blank to use the authenticated actor."><TextInput value={ownerId} onChange={(event) => setOwnerId?.(event.target.value)} /></FormField></div></Panel> : null}
    <Panel title="Draft metadata" description="Display and engine metadata retained by the Pricing domain."><div className="pricing-form-grid"><FormField label="Project name"><TextInput maxLength={200} required value={draft.projectName} onChange={(event) => setDraft((current) => ({ ...current, projectName: event.target.value }))} /></FormField><FormField label="Pricing model"><SelectInput value={draft.pricingModel} onChange={(event) => setDraft((current) => ({ ...current, pricingModel: event.target.value as PricingModel }))}>{models.map((model) => <option key={model} value={model}>{pricingModelLabel(model)}</option>)}</SelectInput></FormField><FormField label="Currency"><TextInput disabled value="USD" /></FormField><FormField label="Configuration ID"><TextInput required value={draft.pricingConfigurationVersionId} onChange={(event) => setDraft((current) => ({ ...current, pricingConfigurationVersionId: event.target.value }))} /></FormField><FormField label="Configuration version"><TextInput min={1} required type="number" value={draft.pricingConfigurationVersion} onChange={(event) => setDraft((current) => ({ ...current, pricingConfigurationVersion: Number(event.target.value) }))} /></FormField><FormField label="Schema version"><TextInput min={1} required type="number" value={draft.configurationSchemaVersion} onChange={(event) => setDraft((current) => ({ ...current, configurationSchemaVersion: Number(event.target.value) }))} /></FormField><FormField label="Engine version"><TextInput required value={draft.engineVersion} onChange={(event) => setDraft((current) => ({ ...current, engineVersion: event.target.value }))} /></FormField><FormField label="Methodology version"><TextInput required value={draft.methodologyVersion} onChange={(event) => setDraft((current) => ({ ...current, methodologyVersion: event.target.value }))} /></FormField></div></Panel>
    <Panel title="Commercial snapshots" description="Complete JSON snapshots are preserved and resubmitted. Cotarion remains authoritative for calculations."><div className="pricing-snapshot-grid">{snapshots.map((key) => <FormField key={key} label={key.replace("Snapshot", " snapshot")}><textarea aria-label={key} className="workspace-textarea pricing-json" required value={snapshotText[key]} onChange={(event) => snapshot(key, event.target.value)} /></FormField>)}</div></Panel>
    <div className="pricing-form-actions"><button className="workspace-button" disabled={busy || Boolean(jsonError) || !submitEnabled} type="submit">{busy ? "Saving…" : submitLabel}</button></div>
  </form></div>;
}
