"use client";
import React, { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { PricingApiClient, type PricingReviewDto, type PricingVersionDto } from "@/presentation/api/pricing-api-client";
import { mapPricingReview, mapPricingVersion, pricingErrorMessage } from "@/presentation/pricing/pricing-view-models";
import { DataTable, EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge } from "@/presentation/components/ui/workspace-primitives";

export function PricingVersionHistoryScreen({ companyId, pricingProjectId }: { companyId: string; pricingProjectId: string }) {
  const api = useMemo(() => new PricingApiClient(companyId), [companyId]); const [items, setItems] = useState<PricingVersionDto[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setItems(await api.versions(pricingProjectId)); } catch (caught) { setError(pricingErrorMessage(caught)); } finally { setLoading(false); } }, [api, pricingProjectId]); useEffect(() => { void load(); }, [load]);
  return <div className="workspace-page"><PageHeader eyebrow="Pricing Project" title="Version History" description="Immutable Pricing Versions and their recorded review outcomes." actions={<Link className="workspace-button workspace-button-secondary" href={`/pricing-projects/${pricingProjectId}`}>Back to Project</Link>} />{loading ? <LoadingState label="Loading Version history" /> : error ? <ErrorState message={error} retry={() => void load()} /> : !items.length ? <EmptyState title="No Pricing Versions" description="No immutable Pricing Version has been saved." /> : <DataTable caption="Pricing Version history" columns={["Version", "Created", "Created by", "Approval", "Reviewer", "Reviewed", "Revision origin"]}>{items.map((source) => { const item = mapPricingVersion(source); return <tr key={item.id}><td>Version {item.number}</td><td>{item.createdLabel}</td><td>{item.createdBy.name}</td><td><StatusBadge status={item.approvalStatus} /></td><td>{item.reviewerLabel}</td><td>{item.reviewedLabel}</td><td>{item.originLabel}</td></tr>; })}</DataTable>}</div>;
}

export function PricingReviewHistoryScreen({ companyId, pricingProjectId }: { companyId: string; pricingProjectId: string }) {
  const api = useMemo(() => new PricingApiClient(companyId), [companyId]); const [items, setItems] = useState<PricingReviewDto[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setItems(await api.reviews(pricingProjectId)); } catch (caught) { setError(pricingErrorMessage(caught)); } finally { setLoading(false); } }, [api, pricingProjectId]); useEffect(() => { void load(); }, [load]);
  return <div className="workspace-page"><PageHeader eyebrow="Pricing Project" title="Review History" description="Quality-review requests, approvals, rejections, actors, and findings." actions={<Link className="workspace-button workspace-button-secondary" href={`/pricing-projects/${pricingProjectId}`}>Back to Project</Link>} />{loading ? <LoadingState label="Loading Review history" /> : error ? <ErrorState message={error} retry={() => void load()} /> : !items.length ? <EmptyState title="No Pricing Reviews" description="No quality-review activity has been recorded." /> : <DataTable caption="Pricing Review history" columns={["Event", "Version", "Actor", "Findings", "Occurred"]}>{items.map((source, index) => { const item = mapPricingReview(source); return <tr key={`${item.pricingVersionId}-${item.type}-${index}`}><td><StatusBadge status={item.type} /></td><td>Version {item.versionNumber}</td><td>{item.actor.name}</td><td>{item.findingsLabel}</td><td>{item.occurredLabel}</td></tr>; })}</DataTable>}</div>;
}
