"use client";
import React, { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { PricingApiClient, PricingApiError, type PricingCommandDto, type PricingDetailDto } from "@/presentation/api/pricing-api-client";
import { formatPricingDate, mapPricingDetail, pricingErrorMessage, pricingModelLabel } from "@/presentation/pricing/pricing-view-models";
import { Card, ConfirmDialog, ErrorState, LoadingState, PageHeader, Panel, StatusBadge } from "@/presentation/components/ui/workspace-primitives";

type Action = "save" | "review" | "approve" | "reject" | "revision" | "archive";
export function PricingProjectDetailScreen({ companyId, pricingProjectId }: { companyId: string; pricingProjectId: string }) {
  const api = useMemo(() => new PricingApiClient(companyId), [companyId]); const [detail, setDetail] = useState<PricingDetailDto | null>(null); const [token, setToken] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<Action | null>(null); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [confirm, setConfirm] = useState<Action | null>(null); const [finding, setFinding] = useState(""); const [conflict, setConflict] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setDetail(await api.detail(pricingProjectId)); } catch (caught) { setError(pricingErrorMessage(caught)); } finally { setLoading(false); } }, [api, pricingProjectId]); useEffect(() => { void load(); }, [load]);
  async function currentToken() { if (token) return token; const editable = await api.edit(pricingProjectId); setToken(editable.concurrencyToken); return editable.concurrencyToken; }
  async function execute(action: Action) {
    setConfirm(null); setBusy(action); setError(null); setNotice(null); setConflict(false);
    try {
      const current = await currentToken(); let result: PricingCommandDto;
      if (action === "save") result = await api.saveVersion(pricingProjectId, current);
      else if (action === "review") { const version = detail?.summary.currentVersion?.number; if (!version) throw new Error("Save a Pricing Version before requesting review."); result = await api.requestQualityReview(pricingProjectId, current, version); }
      else if (action === "approve") result = await api.approve(pricingProjectId, current);
      else if (action === "reject") result = await api.reject(pricingProjectId, current, finding.trim());
      else if (action === "revision") result = await api.beginRevision(pricingProjectId, current);
      else result = await api.archive(pricingProjectId, current);
      setToken(result.concurrencyToken); setFinding(""); setNotice(`${actionLabels[action]} completed.`); await load();
    } catch (caught) { if (caught instanceof PricingApiError && caught.isConcurrencyConflict) { setConflict(true); setToken(null); } setError(caught instanceof Error && !(caught instanceof PricingApiError) ? caught.message : pricingErrorMessage(caught)); }
    finally { setBusy(null); }
  }
  if (loading && !detail) return <LoadingState label="Loading Pricing Project" />; if (!detail) return <ErrorState title="Pricing Project unavailable" message={error ?? "This Pricing Project could not be loaded."} retry={() => void load()} />;
  const view = mapPricingDetail(detail);
  const permitted = new Set(detail.permittedActions);
  return <div className="workspace-page"><PageHeader eyebrow={view.summary.estimateNumber} title={view.summary.projectName} description={`${view.summary.clientLabel} · Owned by ${view.summary.ownerLabel}`} actions={<><Link className="workspace-button workspace-button-secondary" href="/pricing-projects">All Projects</Link>{permitted.has("EDIT_DRAFT") ? <Link className="workspace-button" href={`/pricing-projects/${pricingProjectId}/edit`}>Edit Draft</Link> : null}</>} />
    {notice ? <div className="pricing-notice" role="status">{notice}</div> : null}{error ? <div className="proposal-command-error" role="alert">{error}</div> : null}{conflict ? <div className="pricing-conflict" role="alert"><strong>Project changed</strong><p>This Pricing Project was updated by another action. Reload the latest state before continuing. The failed action was not resubmitted.</p><button className="workspace-button" onClick={() => { setToken(null); setConflict(false); void load(); }} type="button">Reload Project</button></div> : null}
    <div className="workspace-card-grid"><Card label="Status" value={<StatusBadge status={view.summary.status} />} /><Card label="Pricing model" value={view.summary.pricingModelLabel} /><Card label="Current Version" value={view.summary.currentVersionLabel} /><Card label="Last updated" value={view.summary.lastUpdatedLabel} /></div>
    <div className="workspace-two-column"><Panel title="Draft metadata" description="Navigation metadata only; commercial snapshots remain in the editor projection."><dl className="detail-list"><Row label="Project name" value={detail.draft.projectName} /><Row label="Model" value={pricingModelLabel(detail.draft.pricingModel)} /><Row label="Currency" value={detail.draft.currency} /><Row label="Configuration" value={`${detail.draft.pricingConfigurationVersionId} · Version ${detail.draft.pricingConfigurationVersion}`} /><Row label="Schema" value={String(detail.draft.configurationSchemaVersion)} /><Row label="Engine" value={detail.draft.engineVersion} /><Row label="Methodology" value={detail.draft.methodologyVersion} /><Row label="Draft updated" value={view.draftUpdatedLabel} /></dl></Panel><Panel title="Governance position"><dl className="detail-list"><Row label="Version count" value={String(detail.versionCount)} /><Row label="Approved Version" value={detail.approvedVersion ? `Version ${detail.approvedVersion.number} · ${detail.approvedVersion.approvedBy.name} · ${formatPricingDate(detail.approvedVersion.approvedAt)}` : "None"} /><Row label="Review candidate" value={detail.reviewCandidate ? `Version ${detail.reviewCandidate.number} · requested by ${detail.reviewCandidate.requestedBy.name}` : "None"} /></dl></Panel></div>
    <div className="pricing-detail-links"><Link className="workspace-button workspace-button-secondary" href={`/pricing-projects/${pricingProjectId}/versions`}>Version History</Link><Link className="workspace-button workspace-button-secondary" href={`/pricing-projects/${pricingProjectId}/reviews`}>Review History</Link></div>
    <Panel title="Pricing commands" description="Available actions are projected by Cotarion from lifecycle state and your capabilities; every command is validated again when submitted."><div className="pricing-command-bar">{permitted.has("SAVE_VERSION") ? <button className="workspace-button" disabled={Boolean(busy)} onClick={() => void execute("save")} type="button">Save Version</button> : null}{permitted.has("REQUEST_QUALITY_REVIEW") ? <button className="workspace-button workspace-button-secondary" disabled={Boolean(busy)} onClick={() => void execute("review")} type="button">Request Quality Review</button> : null}{permitted.has("APPROVE") ? <button className="workspace-button workspace-button-secondary" disabled={Boolean(busy)} onClick={() => void execute("approve")} type="button">Approve Version</button> : null}{permitted.has("REJECT") ? <button className="workspace-button workspace-button-secondary" disabled={Boolean(busy)} onClick={() => setConfirm("reject")} type="button">Reject Version</button> : null}{permitted.has("BEGIN_REVISION") ? <button className="workspace-button workspace-button-secondary" disabled={Boolean(busy)} onClick={() => void execute("revision")} type="button">Begin Revision</button> : null}{permitted.has("ARCHIVE") ? <button className="workspace-button workspace-button-secondary" disabled={Boolean(busy)} onClick={() => setConfirm("archive")} type="button">Archive Project</button> : null}{permitted.size === 0 ? <p>No Pricing commands are currently available.</p> : null}</div></Panel>
    {confirm === "reject" ? <div aria-labelledby="reject-title" aria-modal="true" className="dialog-backdrop" role="dialog"><form className="proposal-command-dialog" onSubmit={(event) => { event.preventDefault(); if (finding.trim()) void execute("reject"); }}><h2 id="reject-title">Reject Pricing Version</h2><p>Record the required review finding. Cotarion will validate the governance action.</p><label className="workspace-field"><span>Finding</span><textarea autoFocus className="workspace-textarea" maxLength={10000} onChange={(event) => setFinding(event.target.value)} required value={finding} /></label><div className="pricing-dialog-actions"><button className="workspace-button workspace-button-secondary" onClick={() => setConfirm(null)} type="button">Cancel</button><button className="workspace-button" disabled={!finding.trim()} type="submit">Reject Version</button></div></form></div> : null}
    <ConfirmDialog open={confirm === "archive"} title="Archive Pricing Project?" description="This consequential action is submitted to Cotarion for authoritative validation." onCancel={() => setConfirm(null)} onConfirm={() => void execute("archive")} />
  </div>;
}
const actionLabels: Record<Action, string> = { save: "Save Version", review: "Quality Review request", approve: "Approval", reject: "Rejection", revision: "Begin Revision", archive: "Archive" };
function Row({ label, value }: { label: string; value: React.ReactNode }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
