import type { AuthenticatedIdentity } from "@/application/users/application-user-profile";
import { ProposalApplicationError } from "@/application/proposals/proposal-application-errors";
import type { SignatureService } from "@/application/agreements/signature-service";
import type { SignatureQueryService } from "@/application/agreements/signature-query-service";
import type { SignerRole, SigningMode } from "@/application/agreements/signature-repository";
const ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
export interface SignatureHttpDependencies { authenticate:()=>Promise<AuthenticatedIdentity|null>; services:{signatures:SignatureService;signatureQueries:SignatureQueryService}; now?:()=>Date; uuid?:()=>string }
const responseFor=(caught:unknown)=>{const value=caught as{code?:string;message?:string};const status=value.code==="NOT_AUTHENTICATED"?401:value.code==="CAPABILITY_DENIED"||value.code==="COMPANY_SCOPE_VIOLATION"?403:value.code==="PROPOSAL_NOT_FOUND"?404:value.code==="INVALID_REQUEST"?400:value.code?409:500;return Response.json({error:{code:value.code??"TRANSACTION_FAILURE",message:status===500?"Agreement signature request failed.":value.message}},{status});};
export async function handleSignatureHttp(request:Request,path:readonly string[],deps:SignatureHttpDependencies){try{const identity=await deps.authenticate();if(!identity)throw new ProposalApplicationError("NOT_AUTHENTICATED","Authentication required.");const companyId=request.headers.get("x-company-id");if(!companyId||!ID.test(companyId))throw new ProposalApplicationError("INVALID_REQUEST","Company is invalid.");const agreementId=path[0];if(!agreementId||!ID.test(agreementId))throw new ProposalApplicationError("INVALID_REQUEST","Agreement is invalid.");const at=(deps.now??(()=>new Date()))().toISOString();const uuid=deps.uuid??crypto.randomUUID;if(path[1]==="signature-requests"){if(request.method==="POST"&&path.length===2){const body=await request.json() as Record<string,unknown>;const signers=Array.isArray(body.signers)?body.signers.map((entry)=>{const signer=entry as Record<string,unknown>;return{displayName:String(signer.displayName??""),email:String(signer.email??""),role:signer.role as SignerRole,order:Number(signer.order)}}):[];const result=await deps.services.signatures.create(identity,companyId,{agreementId,signers,signingMode:body.signingMode as SigningMode,expiresAt:String(body.expiresAt??""),requestedAt:at,requestIdentity:request.headers.get("idempotency-key")??uuid(),correlationId:uuid()});return Response.json({data:result},{status:result.replay?200:201});}if(request.method==="GET"&&path.length===2)return Response.json({data:await deps.services.signatureQueries.list(identity,companyId,agreementId)});const id=path[2];if(!id||!ID.test(id))throw new ProposalApplicationError("INVALID_REQUEST","Signature Request is invalid.");if(request.method==="GET"&&path.length===3)return Response.json({data:await deps.services.signatureQueries.detail(identity,companyId,agreementId,id)});if(request.method==="POST"&&path[3]==="revoke")return Response.json({data:await deps.services.signatures.revoke(identity,companyId,agreementId,id,at,uuid())});if(request.method==="POST"&&path[3]==="expire")return Response.json({data:await deps.services.signatures.expire(identity,companyId,agreementId,id,at,uuid())});}if(request.method==="GET"&&path[1]==="signing-progress")return Response.json({data:await deps.services.signatureQueries.progress(identity,companyId,agreementId)});throw new ProposalApplicationError("INVALID_REQUEST","Signature endpoint was not found.");}catch(caught){return responseFor(caught);}}
