import { describe, expect, it, vi } from "vitest";
import { handlePublicProposalDecision } from "./proposal-client-decision-public-http";
const requestId = "123e4567-e89b-42d3-a456-426614174000";
function request(body: object = { confirmed: true }) { return new Request("https://example.test/decision", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": requestId }, body: JSON.stringify(body) }); }
describe("public Proposal Decision HTTP boundary", () => {
  it("returns approved client metadata without internal identifiers", async () => { const service = { record: vi.fn().mockResolvedValue({ status: "RECORDED", decision: { outcome: "ACCEPTED", decidedAt: "2026-07-21T12:00:00.000Z" }, title: "Proposal", proposalNumber: "PRO-1", proposalVersionNumber: 2 }) }; const response = await handlePublicProposalDecision(request(), "a".repeat(43), "accept", service as never); const text = await response.text(); expect(response.status).toBe(201); expect(text).toContain("ACCEPTED"); expect(text).not.toMatch(/companyId|proposalVersionId|representationId|deliveryId|revision/); });
  it("rejects missing confirmation, invalid identity, and unavailable Delivery safely", async () => { const service = { record: vi.fn().mockResolvedValue({ status: "UNAVAILABLE" }) }; expect((await handlePublicProposalDecision(request({ confirmed: false }), "a".repeat(43), "accept", service as never)).status).toBe(404); expect((await handlePublicProposalDecision(new Request("https://example.test", { method: "POST", body: "{}" }), "a".repeat(43), "accept", service as never)).status).toBe(404); expect((await handlePublicProposalDecision(request(), "a".repeat(43), "accept", service as never)).status).toBe(404); });
  it("returns a stable conflict without exposing the existing Decision", async () => { const service = { record: vi.fn().mockResolvedValue({ status: "CONFLICT" }) }; const response = await handlePublicProposalDecision(request(), "a".repeat(43), "decline", service as never); expect(response.status).toBe(409); expect(await response.json()).toEqual({ error: { code: "DECISION_CONFLICT", message: "A final Proposal decision has already been recorded." } }); });
});
