ALTER TYPE "ProposalStatus" ADD VALUE IF NOT EXISTS 'EXECUTIVE_AUTHORIZATION';
ALTER TYPE "ProposalStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "ProposalStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
