import { describe, expect, it } from "vitest";
import { ProposalClientDecisionPublicService } from "./proposal-client-decision-public-service";
import type { ProposalClientDecisionRepository, ProposalDecisionReadRecord } from "./proposal-client-decision-repository";
import { HmacProposalDeliveryTokenIssuer } from "@/infrastructure/proposal-deliveries/hmac-proposal-delivery-token-issuer";
const tokens = new HmacProposalDeliveryTokenIssuer("a-strong-secret-with-more-than-thirty-two-bytes"); const issued = tokens.issue("company-1", "delivery-request");
class MemoryRepository implements ProposalClientDecisionRepository {
  decision: ProposalDecisionReadRecord | null = null; available = true; expiresAt = "2026-07-22T12:00:00.000Z";
  async recordFromSecureDelivery(input: Parameters<ProposalClientDecisionRepository["recordFromSecureDelivery"]>[0]) { if (input.tokenDigest !== issued.digest || !this.available || Date.parse(input.decidedAt) >= Date.parse(this.expiresAt)) return { status: "UNAVAILABLE" as const }; if (this.decision) return this.decision.requestIdentity === input.requestIdentity && this.decision.outcome === input.outcome && this.decision.clientDisplayName === input.clientDisplayName && this.decision.clientMessage === input.clientMessage ? { status: "REPLAY" as const, decision: this.decision, title: "Proposal", proposalNumber: "PRO-1", proposalVersionNumber: 1 } : { status: "CONFLICT" as const }; this.decision = { id: input.id, companyId: "company-1", proposalId: "proposal-1", proposalVersionId: "version-1", proposalRepresentationId: "representation-1", deliveryId: "delivery-1", representationType: "PDF", outcome: input.outcome, decidedAt: input.decidedAt, actorType: "SECURE_LINK_CLIENT", clientDisplayName: input.clientDisplayName, clientMessage: input.clientMessage, internalNotes: null, correlationId: input.correlationId, requestIdentity: input.requestIdentity, createdAt: input.decidedAt, timeline: [{ id: "event-1", eventType: `CLIENT_DECISION_${input.outcome}`, occurredAt: input.decidedAt, actorType: "SECURE_LINK_CLIENT", correlationId: input.correlationId }] }; return { status: "RECORDED" as const, decision: this.decision, title: "Proposal", proposalNumber: "PRO-1", proposalVersionNumber: 1 }; }
  async publicStatus(digest: string, at: string) { return digest === issued.digest ? { eligible: this.available && Date.parse(at) < Date.parse(this.expiresAt) && !this.decision, outcome: this.decision?.outcome ?? null } : null; }
  async list() { return this.decision ? [this.decision] : []; } async current() { return this.decision; } async byDelivery() { return this.decision; }
}
describe("ProposalClientDecisionPublicService", () => {
  it("records acceptance once and safely replays the identical request", async () => { const repository = new MemoryRepository(); const service = new ProposalClientDecisionPublicService(repository, tokens, () => "1"); const input = { outcome: "ACCEPTED" as const, decidedAt: "2026-07-21T12:00:00.000Z", clientDisplayName: "Client", clientMessage: "Yes", correlationId: "correlation-1", requestIdentity: "request-1" }; expect((await service.record(issued.token, input)).status).toBe("RECORDED"); expect((await service.record(issued.token, input)).status).toBe("REPLAY"); expect(repository.decision?.proposalVersionId).toBe("version-1"); expect(repository.decision?.proposalRepresentationId).toBe("representation-1"); });
  it("records decline and rejects a later conflicting acceptance", async () => { const repository = new MemoryRepository(); const service = new ProposalClientDecisionPublicService(repository, tokens); const base = { decidedAt: "2026-07-21T12:00:00.000Z", correlationId: "correlation-1", requestIdentity: "request-1" }; expect((await service.record(issued.token, { ...base, outcome: "DECLINED" })).status).toBe("RECORDED"); expect((await service.record(issued.token, { ...base, outcome: "ACCEPTED", requestIdentity: "request-2" })).status).toBe("CONFLICT"); });
  it("rejects revoked, expired, and invalid secure Deliveries", async () => { const repository = new MemoryRepository(); const service = new ProposalClientDecisionPublicService(repository, tokens); repository.available = false; expect((await service.record(issued.token, { outcome: "ACCEPTED", decidedAt: "2026-07-21T12:00:00.000Z", correlationId: "c", requestIdentity: "r" })).status).toBe("UNAVAILABLE"); repository.available = true; expect((await service.record(issued.token, { outcome: "ACCEPTED", decidedAt: repository.expiresAt, correlationId: "c", requestIdentity: "r" })).status).toBe("UNAVAILABLE"); expect((await service.record("invalid", { outcome: "ACCEPTED", decidedAt: "2026-07-21T12:00:00.000Z", correlationId: "c", requestIdentity: "r" })).status).toBe("UNAVAILABLE"); });
});
