"use client";
import React, { useCallback, useEffect, useMemo, useState } from "react";
import { ProposalApiClient, type ProposalClientDecisionDto, type ProposalDeliveryDto, type ProposalDetailDto, type ProposalRepresentationDto, WorkspaceApiError } from "@/presentation/api/proposal-api-client";

export function ProposalDeliveriesPanel({ companyId, proposal }: { companyId: string; proposal: ProposalDetailDto }) {
  const api = useMemo(() => new ProposalApiClient(companyId), [companyId]);
  const [representations, setRepresentations] = useState<ProposalRepresentationDto[]>([]); const [deliveries, setDeliveries] = useState<ProposalDeliveryDto[]>([]);
  const [decisions, setDecisions] = useState<ProposalClientDecisionDto[]>([]);
  const [representationId, setRepresentationId] = useState(""); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [role, setRole] = useState(""); const [expiresAt, setExpiresAt] = useState("");
  const [secureUrl, setSecureUrl] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { const [artifacts, history, decisionHistory] = await Promise.all([api.representationHistory(proposal.id), api.deliveryHistory(proposal.id), api.decisionHistory(proposal.id)]); setRepresentations(artifacts); setDeliveries(history); setDecisions(decisionHistory); } catch (caught) { setError(caught instanceof WorkspaceApiError ? caught.message : "Delivery history could not be loaded."); } }, [api, proposal.id]);
  useEffect(() => { void load(); }, [load]);
  async function create(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { const result = await api.createDelivery(proposal.id, representationId, { recipients: [{ name, email, recipientRole: role }], expiresAt: new Date(expiresAt).toISOString() }); setSecureUrl(`${window.location.origin}${result.secureUrl}`); await load(); } catch (caught) { setError(caught instanceof WorkspaceApiError ? caught.message : "Secure Delivery could not be created."); } finally { setBusy(false); } }
  async function revoke(deliveryId: string) { setBusy(true); try { await api.revokeDelivery(proposal.id, deliveryId); await load(); } catch (caught) { setError(caught instanceof WorkspaceApiError ? caught.message : "Delivery could not be revoked."); } finally { setBusy(false); } }
  return <section aria-labelledby="proposal-deliveries-title" className="proposal-panel"><h2 id="proposal-deliveries-title">Client Delivery</h2><p>Make one immutable Representation available through an expiring secure link. Access is not Client Acceptance.</p>{error ? <p className="proposal-command-error" role="alert">{error}</p> : null}
    {proposal.permittedActions.createDelivery ? <form className="proposal-command-dialog" onSubmit={create}><label className="workspace-field"><span>Representation</span><select className="workspace-input" required value={representationId} onChange={(event) => setRepresentationId(event.target.value)}><option value="">Select Representation</option>{representations.map((item) => <option key={item.id} value={item.id}>Version {item.proposalVersionNumber} · {item.representationType}</option>)}</select></label><label className="workspace-field"><span>Recipient name</span><input className="workspace-input" required value={name} onChange={(event) => setName(event.target.value)} /></label><label className="workspace-field"><span>Recipient email</span><input className="workspace-input" required type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label className="workspace-field"><span>Recipient role</span><input className="workspace-input" value={role} onChange={(event) => setRole(event.target.value)} /></label><label className="workspace-field"><span>Expires</span><input className="workspace-input" required type="datetime-local" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} /></label><button className="workspace-button" disabled={busy || !representations.length} type="submit">Create secure Delivery</button></form> : null}
    {secureUrl ? <div><label className="workspace-field"><span>Secure link</span><input className="workspace-input" readOnly value={secureUrl} /></label><button className="workspace-button" onClick={() => void navigator.clipboard.writeText(secureUrl)} type="button">Copy secure link</button></div> : null}
    <h3>Delivery history</h3>{!deliveries.length ? <p>No Deliveries recorded.</p> : <ul>{deliveries.map((delivery) => <li key={delivery.id}>{delivery.status} · {delivery.representationType} · {delivery.recipients.map((recipient) => recipient.email).join(", ")} · {delivery.accesses.length} access{delivery.accesses.length === 1 ? "" : "es"}{delivery.permittedActions.revoke ? <button className="table-primary-link" disabled={busy} onClick={() => void revoke(delivery.id)} type="button">Revoke</button> : null}</li>)}</ul>}
    <h3>Client Decision timeline</h3>{!decisions.length ? <p>No final Client Decision recorded.</p> : <ul>{decisions.map((decision) => <li key={decision.id}>{decision.outcome} · {new Date(decision.decidedAt).toLocaleString()}{decision.clientDisplayName ? ` · ${decision.clientDisplayName}` : ""}{decision.clientMessage ? <blockquote>{decision.clientMessage}</blockquote> : null}</li>)}</ul>}
  </section>;
}
