"use client";
import React, { useEffect, useRef, useState } from "react";
type Outcome = "ACCEPTED" | "DECLINED";
export function ProposalClientDecisionScreen({ token }: { token: string }) {
  const [artifactUrl, setArtifactUrl] = useState<string | null>(null); const [contentType, setContentType] = useState("");
  const [title, setTitle] = useState("Proposal"); const [number, setNumber] = useState(""); const [version, setVersion] = useState("");
  const [eligible, setEligible] = useState(false); const [outcome, setOutcome] = useState<string>("NONE");
  const [name, setName] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const requestIdentities = useRef<Partial<Record<Outcome, string>>>({});
  useEffect(() => { let url: string | null = null; void fetch(`/api/public/proposal-deliveries/${encodeURIComponent(token)}`, { cache: "no-store" }).then(async (response) => { if (!response.ok) throw new Error(); const blob = await response.blob(); url = URL.createObjectURL(blob); setArtifactUrl(url); setContentType(response.headers.get("content-type") ?? ""); setTitle(decodeURIComponent(response.headers.get("x-proposal-title") ?? "Proposal")); setNumber(response.headers.get("x-proposal-number") ?? ""); setVersion(response.headers.get("x-proposal-version") ?? ""); setEligible(response.headers.get("x-client-decision-eligible") === "true"); setOutcome(response.headers.get("x-client-decision-status") ?? "NONE"); }).catch(() => setError("This secure Proposal link is unavailable.")); return () => { if (url) URL.revokeObjectURL(url); }; }, [token]);
  async function decide(selected: Outcome) { if (!eligible || busy || !window.confirm(`Confirm that you want to ${selected === "ACCEPTED" ? "accept" : "decline"} this Proposal? This decision is final.`)) return; setBusy(true); setError(null); requestIdentities.current[selected] ??= crypto.randomUUID(); try { const response = await fetch(`/api/public/proposal-deliveries/${encodeURIComponent(token)}/decisions/${selected === "ACCEPTED" ? "accept" : "decline"}`, { method: "POST", headers: { "content-type": "application/json", "idempotency-key": requestIdentities.current[selected]! }, body: JSON.stringify({ confirmed: true, clientDisplayName: name, clientMessage: message }) }); const result = await response.json(); if (!response.ok) throw new Error(result?.error?.message); setOutcome(result.data.outcome); setEligible(false); } catch (caught) { setError(caught instanceof Error && caught.message ? caught.message : "The decision could not be recorded."); } finally { setBusy(false); } }
  return <main className="proposal-workspace" style={{ maxWidth: 960, margin: "0 auto", padding: 24 }}><h1>{title}</h1><p>{number}{version ? ` · Version ${version}` : ""}</p>{error ? <p role="alert">{error}</p> : null}{artifactUrl ? contentType.includes("html") ? <iframe title="Proposal preview" sandbox="" src={artifactUrl} style={{ width: "100%", minHeight: 540 }} /> : <a href={artifactUrl} download={`${number || "proposal"}.pdf`}>Download Proposal PDF</a> : <p>Loading Proposal…</p>}{outcome !== "NONE" ? <h2>Final decision: {outcome}</h2> : null}{eligible ? <section aria-labelledby="decision-title"><h2 id="decision-title">Your decision</h2><label className="workspace-field"><span>Your name (optional)</span><input className="workspace-input" maxLength={200} value={name} onChange={(event) => setName(event.target.value)} /></label><label className="workspace-field"><span>Message (optional)</span><textarea className="workspace-input" maxLength={5000} value={message} onChange={(event) => setMessage(event.target.value)} /></label><div><button className="workspace-button" disabled={busy} onClick={() => void decide("ACCEPTED")} type="button">Accept Proposal</button><button className="workspace-button" disabled={busy} onClick={() => void decide("DECLINED")} type="button">Decline Proposal</button></div><p>Viewing this Proposal is not acceptance. A decision is recorded only after confirmation.</p></section> : null}</main>;
}
