import type { AuthenticatedIdentity } from "@/application/users/application-user-profile";
import { ProposalApplicationError } from "@/application/proposals/proposal-application-errors";
import { PROPOSAL_CAPABILITIES, type ProposalActorContextProvider, type ProposalCapabilityEvaluator } from "@/application/proposals/proposal-capabilities";
import type { AgreementRepository } from "./agreement-repository";
export class AgreementQueryService {
  constructor(private readonly actors: ProposalActorContextProvider, private readonly capabilities: ProposalCapabilityEvaluator, private readonly repository: AgreementRepository) {}
  async list(identity: AuthenticatedIdentity, companyId: string, proposalId: string) { const capabilities = await this.auth(identity, companyId); const items = await this.repository.list(companyId, proposalId); const accepted = items.length ? null : await this.repository.acceptedSource(companyId, proposalId); return { items, permittedActions: { generate: Boolean(accepted) && capabilities.has(PROPOSAL_CAPABILITIES.GENERATE_AGREEMENT) } }; }
  async detail(identity: AuthenticatedIdentity, companyId: string, proposalId: string, agreementId: string) { await this.auth(identity, companyId); const value = await this.repository.detail(companyId, proposalId, agreementId); if (!value) throw new ProposalApplicationError("PROPOSAL_NOT_FOUND", "Agreement was not found."); return value; }
  async artifact(identity: AuthenticatedIdentity, companyId: string, proposalId: string, agreementId: string, type: "HTML" | "PDF") { await this.auth(identity, companyId); const value = await this.repository.artifact(companyId, proposalId, agreementId, type); if (!value) throw new ProposalApplicationError("PROPOSAL_NOT_FOUND", "Agreement artifact was not found."); return value; }
  private async auth(identity: AuthenticatedIdentity, companyId: string) { const actor = await this.actors.load(identity); if (!actor?.active) throw new ProposalApplicationError("NOT_AUTHENTICATED", "Authentication is required."); if (actor.companyId !== companyId) throw new ProposalApplicationError("COMPANY_SCOPE_VIOLATION", "Company scope is invalid."); const capabilities = await this.capabilities.capabilitiesFor(actor); if (!capabilities.has(PROPOSAL_CAPABILITIES.VIEW_AGREEMENT)) throw new ProposalApplicationError("CAPABILITY_DENIED", "agreement:view is required."); return capabilities; }
}
