import { describe, expect, it, vi } from "vitest";
import { PROPOSAL_CAPABILITIES } from "@/application/proposals/proposal-capabilities";
import { AgreementExecutionService } from "./execution-service";
import { AgreementExecutionQueryService } from "./execution-query-service";
const identity = { id: "auth", email: "user@example.com", name: "User" };
const execution = { id: "execution-1", agreementId: "agreement-1", agreementVersion: 1, executed: true as const, executedAt: "2026-07-21T12:00:00.000Z", executedBy: "user-1", artifactChecksum: "checksum", determination: "ALL_REQUIRED_SIGNERS_SIGNED" as const, signerSummary: [{ role: "CLIENT", displayName: "Client", signedAt: "2026-07-21T11:00:00.000Z", signatureEvidenceReference: "evidence-1" }], history: [] };
function setup(capabilities = [PROPOSAL_CAPABILITIES.EXECUTE_AGREEMENT, PROPOSAL_CAPABILITIES.VIEW_EXECUTION]) { const repository = { execute: vi.fn(async () => ({ execution, replay: false })), detail: vi.fn(async () => null), list: vi.fn(async () => [execution]), eligibility: vi.fn(async () => ({ eligible: true, reason: "ALL_REQUIRED_SIGNERS_SIGNED" })) }; const actors = { load: async () => ({ userId: "user-1", companyId: "company-1", active: true }) }; const evaluator = { capabilitiesFor: async () => new Set(capabilities) }; return { repository, service: new AgreementExecutionService(actors, evaluator, repository, () => "1"), query: new AgreementExecutionQueryService(actors, evaluator, repository) }; }
describe("Agreement Execution", () => {
  it("executes through the transactional authority and preserves immutable evidence references", async () => { const current = setup(); const result = await current.service.execute(identity, "company-1", { agreementId: "agreement-1", executedAt: execution.executedAt, requestIdentity: "request-1", correlationId: "correlation-1" }); expect(result.execution).toEqual(execution); expect(current.repository.execute).toHaveBeenCalledWith(expect.objectContaining({ companyId: "company-1", executedByUserId: "user-1" })); });
  it("enforces authorization and Company isolation", async () => { await expect(setup([]).service.execute(identity, "company-1", { agreementId: "agreement-1", executedAt: execution.executedAt, requestIdentity: "r", correlationId: "c" })).rejects.toMatchObject({ code: "CAPABILITY_DENIED" }); await expect(setup().service.execute(identity, "company-2", { agreementId: "agreement-1", executedAt: execution.executedAt, requestIdentity: "r", correlationId: "c" })).rejects.toMatchObject({ code: "COMPANY_SCOPE_VIOLATION" }); });
  it("projects eligibility and history through direct repository reads", async () => { const current = setup(); expect((await current.query.detail(identity, "company-1", "agreement-1")).permittedActions.execute).toBe(true); expect(await current.query.list(identity, "company-1", "agreement-1")).toEqual([execution]); });
});
